name: Test
on:
  push:
    branches-ignore:
      - "gh-pages"
    paths-ignore:
      - "**/README.md"
      - "docs/*"
      - "mkdocs.yml"
jobs:
  unit_tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
        poetry-version: ["1.1.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Poetry install
        run: poetry install
      - name: Run tests
        run: poetry run pytest -vv
        env:
          HYPOTHESIS_PROFILE: debug
