name: docs
on:
  push:
    branches:
      - main
      - hatch
    paths:
      - ".github/workflows/docs.yml"
      - "docs/**"
      - "mkdocs.yml"
      - "harborapi/**"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Ensure latest pip
        run: python -m pip install --upgrade pip

      - name: Install ourself
        run: |
          pip install -e .

      - name: Install hatch
        run: pip install hatch

      - name: Build documentation and publish
        run: hatch run docs:mkdocs gh-deploy --force
